module.exports = function () {
  var data = {
    joboffer: [
      {
        id: 1,
        description: "Se necesita chofer para camioneta",
        licenseTypeRequired: "A1",
        experienceYearsRequired: 2,
        appliers: 0,
        vehicle: "Camioneta",
        idEmployer: 1,
      },
    ],
    driver: [
      {
        id: 1,
        employed: false,
        licenseType: "A-IIIb",
        license: "E64294438",
        rol: "Driver",
        dni: "07084031",
        name: "Aldis",
        lastname: "Ruddell",
        email: "aruddell0@wunderground.com",
        password: "6dTYI5v",
        dateOfBirth: "19921013",
        plan: "Shark",
      },
      {
        id: 2,
        employed: true,
        licenseType: "A-IIIa",
        license: "X20234595",
        rol: "Driver",
        dni: "11467582",
        name: "Denis",
        lastname: "Gliddon",
        email: "dgliddon1@twitpic.com",
        password: "MbTtjTAU",
        dateOfBirth: "19870903",
        plan: "Sharky",
      },
      {
        id: 3,
        employed: true,
        licenseType: "A-IIa",
        license: "P86083487",
        rol: "Employer",
        dni: "01993289",
        name: "Duncan",
        lastname: "Tenwick",
        email: "dtenwick2@businesswire.com",
        password: "pRESdN3w1N",
        dateOfBirth: "19851219",
        plan: "Sharky",
      },
      {
        id: 4,
        employed: true,
        licenseType: "A-IIIb",
        license: "F24134697",
        rol: "Employer",
        dni: "40908240",
        name: "Farlie",
        lastname: "Ropcke",
        email: "fropcke3@slideshare.net",
        password: "JHzWQ44lA",
        dateOfBirth: "19840505",
        plan: "Sharky",
      },
      {
        id: 5,
        employed: false,
        licenseType: "A-IIa",
        license: "Y09550720",
        rol: "Employer",
        dni: "78726801",
        name: "Northrup",
        lastname: "Book",
        email: "nbook4@intel.com",
        password: "4mPYHpeFLs",
        dateOfBirth: "19950522",
        plan: "Sharky",
      },
      {
        id: 6,
        employed: true,
        licenseType: "A-IIIb",
        license: "A85736647",
        rol: "Employer",
        dni: "57152417",
        name: "Gil",
        lastname: "Cubbini",
        email: "gcubbini5@hp.com",
        password: "2srZZQDym4",
        dateOfBirth: "20010728",
        plan: "Shark",
      },
      {
        id: 7,
        employed: false,
        licenseType: "A-I",
        license: "C28071301",
        rol: "Driver",
        dni: "15155329",
        name: "Silvester",
        lastname: "Moffatt",
        email: "smoffatt6@netlog.com",
        password: "caizWtsxfX",
        dateOfBirth: "19990606",
        plan: "WhiteShark",
      },
      {
        id: 8,
        employed: false,
        licenseType: "A-IIb",
        license: "N25838171",
        rol: "Driver",
        dni: "20918216",
        name: "Gardy",
        lastname: "Brattan",
        email: "gbrattan7@umich.edu",
        password: "qB7yydBltRD",
        dateOfBirth: "19971101",
        plan: "WhiteShark",
      },
      {
        id: 9,
        employed: true,
        licenseType: "A-IIa",
        license: "N06074683",
        rol: "Driver",
        dni: "93493160",
        name: "Aluin",
        lastname: "Corneliussen",
        email: "acorneliussen8@indiegogo.com",
        password: "VujRKCirL7Hd",
        dateOfBirth: "19910628",
        plan: "Sharky",
      },
      {
        id: 10,
        employed: false,
        licenseType: "A-IIIb",
        license: "O24935256",
        rol: "Employer",
        dni: "25099854",
        name: "Chad",
        lastname: "Bowlesworth",
        email: "cbowlesworth9@bloomberg.com",
        password: "6bJpqRQy",
        dateOfBirth: "19991128",
        plan: "Sharky",
      },
      {
        id: 11,
        employed: false,
        licenseType: "A-I",
        license: "W54920698",
        rol: "Employer",
        dni: "02778397",
        name: "Denis",
        lastname: "Murphy",
        email: "dmurphya@noaa.gov",
        password: "DoFAoK6VSo",
        dateOfBirth: "19900315",
        plan: "Sharky",
      },
      {
        id: 12,
        employed: true,
        licenseType: "A-I",
        license: "P18071776",
        rol: "Driver",
        dni: "57255103",
        name: "Thorin",
        lastname: "Skinn",
        email: "tskinnb@omniture.com",
        password: "fpk2cSZomN",
        dateOfBirth: "20001218",
        plan: "Shark",
      },
      {
        id: 13,
        employed: true,
        licenseType: "A-IIIb",
        license: "R97248425",
        rol: "Driver",
        dni: "45626157",
        name: "Siffre",
        lastname: "Chesley",
        email: "schesleyc@furl.net",
        password: "YoA3YAw9T4B",
        dateOfBirth: "19880806",
        plan: "Shark",
      },
      {
        id: 14,
        employed: true,
        licenseType: "A-I",
        license: "J40643801",
        rol: "Driver",
        dni: "78526434",
        name: "Tye",
        lastname: "Bly",
        email: "tblyd@gmpg.org",
        password: "0VP0ua",
        dateOfBirth: "19860712",
        plan: "Shark",
      },
      {
        id: 15,
        employed: true,
        licenseType: "A-IIIa",
        license: "F12455433",
        rol: "Driver",
        dni: "82374556",
        name: "Rabbi",
        lastname: "Howley",
        email: "rhowleye@businesswire.com",
        password: "dD0OBa",
        dateOfBirth: "19870915",
        plan: "Shark",
      },
      {
        id: 16,
        employed: true,
        licenseType: "A-IIIa",
        license: "U73723492",
        rol: "Driver",
        dni: "72761547",
        name: "Haslett",
        lastname: "Keri",
        email: "hkerif@sina.com.cn",
        password: "j3xJsb7a",
        dateOfBirth: "19820205",
        plan: "WhiteShark",
      },
      {
        id: 17,
        employed: true,
        licenseType: "A-IIIa",
        license: "D97942538",
        rol: "Employer",
        dni: "59716917",
        name: "Angel",
        lastname: "Liepins",
        email: "aliepinsg@reddit.com",
        password: "xgKbf5oYm",
        dateOfBirth: "20020112",
        plan: "WhiteShark",
      },
      {
        id: 18,
        employed: true,
        licenseType: "A-IIIa",
        license: "U71685838",
        rol: "Employer",
        dni: "33591138",
        name: "Danya",
        lastname: "Hogbin",
        email: "dhogbinh@aol.com",
        password: "fkxd9i54t",
        dateOfBirth: "19980915",
        plan: "Sharky",
      },
      {
        id: 19,
        employed: false,
        licenseType: "A-IIIb",
        license: "U98282886",
        rol: "Driver",
        dni: "65560797",
        name: "Jessey",
        lastname: "Seemmonds",
        email: "jseemmondsi@mayoclinic.com",
        password: "fXOT4C",
        dateOfBirth: "20000304",
        plan: "Sharky",
      },
      {
        id: 20,
        employed: false,
        licenseType: "A-IIa",
        license: "S23033020",
        rol: "Employer",
        dni: "41042529",
        name: "Euell",
        lastname: "Garvie",
        email: "egarviej@dyndns.org",
        password: "sT1QBFesgT",
        dateOfBirth: "19931109",
        plan: "Sharky",
      },
      {
        id: 21,
        employed: false,
        licenseType: "A-I",
        license: "U07649054",
        rol: "Driver",
        dni: "18134733",
        name: "Antone",
        lastname: "Loyd",
        email: "aloydk@scientificamerican.com",
        password: "wmPReCBi8",
        dateOfBirth: "19991122",
        plan: "Shark",
      },
      {
        id: 22,
        employed: false,
        licenseType: "A-I",
        license: "F58748254",
        rol: "Driver",
        dni: "59414511",
        name: "Ode",
        lastname: "Serraillier",
        email: "oserraillierl@ucla.edu",
        password: "OtZkqA",
        dateOfBirth: "19901128",
        plan: "Sharky",
      },
      {
        id: 23,
        employed: false,
        licenseType: "A-IIIb",
        license: "D31660947",
        rol: "Employer",
        dni: "96082708",
        name: "Wilt",
        lastname: "Wodham",
        email: "wwodhamm@cbslocal.com",
        password: "AIa9PsvF",
        dateOfBirth: "19840809",
        plan: "Shark",
      },
      {
        id: 24,
        employed: false,
        licenseType: "A-IIb",
        license: "Q84302817",
        rol: "Employer",
        dni: "33449157",
        name: "Xever",
        lastname: "Komorowski",
        email: "xkomorowskin@bandcamp.com",
        password: "QEHbApVUJm",
        dateOfBirth: "19951127",
        plan: "Shark",
      },
      {
        id: 25,
        employed: true,
        licenseType: "A-IIIa",
        license: "Z04447790",
        rol: "Driver",
        dni: "00966861",
        name: "Fax",
        lastname: "Svanetti",
        email: "fsvanettio@gravatar.com",
        password: "o1IPU8q",
        dateOfBirth: "19960510",
        plan: "Sharky",
      },
      {
        id: 26,
        employed: true,
        licenseType: "A-I",
        license: "V33970721",
        rol: "Employer",
        dni: "43452274",
        name: "Adams",
        lastname: "Fuster",
        email: "afusterp@nature.com",
        password: "OCioLWWING",
        dateOfBirth: "19990702",
        plan: "Sharky",
      },
      {
        id: 27,
        employed: false,
        licenseType: "A-IIb",
        license: "X03120952",
        rol: "Employer",
        dni: "60529301",
        name: "Holly",
        lastname: "Herkess",
        email: "hherkessq@indiatimes.com",
        password: "tdUmtCYSbc",
        dateOfBirth: "19821011",
        plan: "WhiteShark",
      },
      {
        id: 28,
        employed: false,
        licenseType: "A-IIa",
        license: "P58725121",
        rol: "Driver",
        dni: "60051949",
        name: "Freeland",
        lastname: "Enderwick",
        email: "fenderwickr@meetup.com",
        password: "NqFlaYnWx",
        dateOfBirth: "19800827",
        plan: "Sharky",
      },
      {
        id: 29,
        employed: false,
        licenseType: "A-I",
        license: "J24869756",
        rol: "Driver",
        dni: "50204609",
        name: "Art",
        lastname: "Alvarado",
        email: "aalvarados@youtube.com",
        password: "sq5wUTo",
        dateOfBirth: "19870311",
        plan: "Sharky",
      },
      {
        id: 30,
        employed: false,
        licenseType: "A-IIa",
        license: "Q77612547",
        rol: "Driver",
        dni: "55337850",
        name: "Renard",
        lastname: "Spencers",
        email: "rspencerst@moonfruit.com",
        password: "W7QPP8ZKn",
        dateOfBirth: "19940202",
        plan: "WhiteShark",
      },
      {
        id: 31,
        employed: false,
        licenseType: "A-IIIa",
        license: "C94350178",
        rol: "Driver",
        dni: "20290996",
        name: "Burty",
        lastname: "O'Shirine",
        email: "boshirineu@barnesandnoble.com",
        password: "1XN6vVKtWDx",
        dateOfBirth: "19970214",
        plan: "Sharky",
      },
      {
        id: 32,
        employed: true,
        licenseType: "A-IIIa",
        license: "I51227312",
        rol: "Employer",
        dni: "33327672",
        name: "Slade",
        lastname: "Glauber",
        email: "sglauberv@comcast.net",
        password: "Yt14kk",
        dateOfBirth: "20020129",
        plan: "WhiteShark",
      },
      {
        id: 33,
        employed: true,
        licenseType: "A-IIIb",
        license: "F94887916",
        rol: "Employer",
        dni: "10003012",
        name: "Haydon",
        lastname: "Gantley",
        email: "hgantleyw@gizmodo.com",
        password: "DjNZjeRCQNEx",
        dateOfBirth: "19931106",
        plan: "Shark",
      },
      {
        id: 34,
        employed: true,
        licenseType: "A-IIa",
        license: "U46642143",
        rol: "Driver",
        dni: "62689559",
        name: "Emmett",
        lastname: "Stapels",
        email: "estapelsx@free.fr",
        password: "Gz4YmiA8Bd",
        dateOfBirth: "19820805",
        plan: "Sharky",
      },
      {
        id: 35,
        employed: true,
        licenseType: "A-I",
        license: "T93167272",
        rol: "Driver",
        dni: "54821428",
        name: "Knox",
        lastname: "Joannidi",
        email: "kjoannidiy@gizmodo.com",
        password: "Nlnc6oZ",
        dateOfBirth: "19840425",
        plan: "Sharky",
      },
      {
        id: 36,
        employed: true,
        licenseType: "A-I",
        license: "N36961202",
        rol: "Driver",
        dni: "57161191",
        name: "Olvan",
        lastname: "Whitemarsh",
        email: "owhitemarshz@hugedomains.com",
        password: "p8rlA9H",
        dateOfBirth: "20001121",
        plan: "Sharky",
      },
      {
        id: 37,
        employed: false,
        licenseType: "A-I",
        license: "K99321235",
        rol: "Employer",
        dni: "85311103",
        name: "Rodolph",
        lastname: "Lippo",
        email: "rlippo10@newyorker.com",
        password: "LUOYr6E18",
        dateOfBirth: "19850830",
        plan: "Sharky",
      },
      {
        id: 38,
        employed: false,
        licenseType: "A-IIIb",
        license: "U07543219",
        rol: "Driver",
        dni: "20523261",
        name: "Pail",
        lastname: "Wyllt",
        email: "pwyllt11@facebook.com",
        password: "0gUrrnzYKw",
        dateOfBirth: "19840902",
        plan: "Sharky",
      },
      {
        id: 39,
        employed: true,
        licenseType: "A-IIIa",
        license: "F86670830",
        rol: "Employer",
        dni: "44315495",
        name: "Rob",
        lastname: "Kenton",
        email: "rkenton12@a8.net",
        password: "yN3rVHD43",
        dateOfBirth: "19950916",
        plan: "Shark",
      },
      {
        id: 40,
        employed: true,
        licenseType: "A-I",
        license: "E85831471",
        rol: "Employer",
        dni: "33880745",
        name: "Shell",
        lastname: "Cowans",
        email: "scowans13@pen.io",
        password: "wSYZls",
        dateOfBirth: "19860717",
        plan: "Shark",
      },
      {
        id: 41,
        employed: false,
        licenseType: "A-IIIb",
        license: "V27070962",
        rol: "Driver",
        dni: "30977880",
        name: "Andrew",
        lastname: "Whitworth",
        email: "awhitworth14@360.cn",
        password: "AJog9sgjnZCj",
        dateOfBirth: "19850514",
        plan: "Sharky",
      },
      {
        id: 42,
        employed: true,
        licenseType: "A-I",
        license: "B73293082",
        rol: "Driver",
        dni: "94721361",
        name: "Nevil",
        lastname: "Emlen",
        email: "nemlen15@zdnet.com",
        password: "55R3yOf",
        dateOfBirth: "19980124",
        plan: "Sharky",
      },
      {
        id: 43,
        employed: true,
        licenseType: "A-I",
        license: "G73004702",
        rol: "Driver",
        dni: "99317407",
        name: "Mord",
        lastname: "McGourty",
        email: "mmcgourty16@spiegel.de",
        password: "hpr7QPJ",
        dateOfBirth: "19950710",
        plan: "Sharky",
      },
      {
        id: 44,
        employed: false,
        licenseType: "A-IIa",
        license: "F17437469",
        rol: "Employer",
        dni: "51694269",
        name: "Jan",
        lastname: "Domino",
        email: "jdomino17@hhs.gov",
        password: "QUs9r9gYbbp",
        dateOfBirth: "19850225",
        plan: "Sharky",
      },
      {
        id: 45,
        employed: true,
        licenseType: "A-I",
        license: "I69784990",
        rol: "Employer",
        dni: "74783588",
        name: "Cody",
        lastname: "Sommerville",
        email: "csommerville18@i2i.jp",
        password: "zssLre3X5nCw",
        dateOfBirth: "19951123",
        plan: "Shark",
      },
      {
        id: 46,
        employed: false,
        licenseType: "A-IIb",
        license: "F08590305",
        rol: "Driver",
        dni: "36205127",
        name: "Conrade",
        lastname: "Josovitz",
        email: "cjosovitz19@admin.ch",
        password: "juxnmOFiFWl",
        dateOfBirth: "19960723",
        plan: "Sharky",
      },
      {
        id: 47,
        employed: true,
        licenseType: "A-IIb",
        license: "K31638540",
        rol: "Driver",
        dni: "98944740",
        name: "Maison",
        lastname: "Thorburn",
        email: "mthorburn1a@privacy.gov.au",
        password: "vTRE1WMCsCuy",
        dateOfBirth: "19860717",
        plan: "WhiteShark",
      },
      {
        id: 48,
        employed: true,
        licenseType: "A-I",
        license: "P21042926",
        rol: "Driver",
        dni: "59565071",
        name: "Weylin",
        lastname: "Burcher",
        email: "wburcher1b@booking.com",
        password: "Gwpwo9X1",
        dateOfBirth: "19890626",
        plan: "Sharky",
      },
      {
        id: 49,
        employed: false,
        licenseType: "A-IIb",
        license: "N38512733",
        rol: "Driver",
        dni: "16205152",
        name: "Urbain",
        lastname: "Towne",
        email: "utowne1c@redcross.org",
        password: "j6tO4hsHv",
        dateOfBirth: "19961223",
        plan: "WhiteShark",
      },
      {
        id: 50,
        employed: true,
        licenseType: "A-IIIb",
        license: "S25144440",
        rol: "Employer",
        dni: "21098989",
        name: "Collin",
        lastname: "Signori",
        email: "csignori1d@trellian.com",
        password: "aDygc3Ez",
        dateOfBirth: "19981120",
        plan: "Shark",
      },
    ],
  };

  return data;
};
